name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your_server_ip >> ~/.ssh/known_hosts

      - name: Build and Deploy
        run: |
          ssh c94140@91.201.52.229 << 'EOF'
            cd /poker52.na4u.ru/app
            git pull origin main
            npm install
            npm install --only=dev
            npm run build
          EOF
