name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 91.201.52.229 >> ~/.ssh/known_hosts

      - name: Build and Deploy
        run: |
          ssh c94140@91.201.52.229 << 'EOF'
            source ~/.bashrc
            # echo $PATH
            # which npm
            cd poker52.na4u.ru/app
            git pull origin main
            /home/c94140/.nvm/versions/node/v22.4.1/bin/npm -v
            # npm install
            # npm install --only=dev
            # /home/c94140/.nvm/versions/node/v22.4.1/bin/npm run build
          EOF
